In [1]:
from fastai2.tabular.all import *

In [2]:
f = open("output/engineered_datasets.pickle","rb")
train_x, train_y, final_test, num_x, cat_x, cat_x_ind = pickle.load(f)
train_x['SalePrice'] = train_y

In [3]:
dls = TabularDataLoaders.from_df(train_x, path='bla', y_names="SalePrice",
    cat_names = cat_x,
    cont_names = num_x,
    procs = [Categorify, FillMissing, Normalize])

In [4]:


learn = tabular_learner(dls, loss_func=MSELossFlat(), 
                        metrics=rmse)
learn.fit_one_cycle(3)

In [5]:
# final_test.drop(columns=['Id','Utilities'], inplace=True)
final_test['BsmtFinSF1'] = final_test['BsmtFinSF1'].fillna(0)
final_test['BsmtFinSF2'] = final_test['BsmtFinSF2'].fillna(0)
final_test['BsmtUnfSF'] = final_test['BsmtUnfSF'].fillna(0)
final_test['TotalBsmtSF'] = final_test['TotalBsmtSF'].fillna(0)
final_test['BsmtFullBath'] = final_test['BsmtFullBath'].fillna(0)
final_test['KitchenQual'] = final_test['KitchenQual'].fillna(train_x['KitchenQual'].mean())
final_test['Functional'] = final_test['Functional'].fillna(train_x['Functional'].mean())
final_test['GarageCars'] = final_test['GarageCars'].fillna(0)
final_test['GarageArea'] = final_test['GarageArea'].fillna(0)
final_test['SimplFunctional'] = final_test['SimplFunctional'].fillna(0)
final_test['SimplKitchenQual'] = final_test['SimplKitchenQual'].fillna(0)
final_test['KitchenScore'] = final_test['KitchenScore'].fillna(0)
final_test['SimplFunctional'] = final_test['SimplFunctional'].fillna(train_x['SimplFunctional'].mean())
final_test['SimplKitchenScore'] = final_test['SimplKitchenScore'].fillna(train_x['SimplKitchenScore'].mean())
final_test['TotalBath'] = final_test['TotalBath'].fillna(1)
final_test['AllSF'] = final_test['AllSF'].fillna(train_x['AllSF'].mean())
final_test['AllSF_2'] = final_test['AllSF_2'].fillna(train_x['AllSF_2'].mean())
final_test['AllSF_3'] = final_test['AllSF_3'].fillna(train_x['AllSF_3'].mean())
final_test['AllSF_sq'] = final_test['AllSF_sq'].fillna(train_x['AllSF_sq'].mean())
final_test['GarageCars_2'] = final_test['GarageCars_2'].fillna(train_x['GarageCars_2'].mean())
final_test['GarageCars_3'] = final_test['GarageCars_3'].fillna(train_x['GarageCars_3'].mean())
final_test['GarageCars_sq'] = final_test['GarageCars_sq'].fillna(train_x['GarageCars_sq'].mean())
final_test['TotalBath_2'] = final_test['TotalBath_2'].fillna(train_x['TotalBath_2'].mean())
final_test['TotalBath_3'] = final_test['TotalBath_3'].fillna(train_x['TotalBath_3'].mean())
final_test['TotalBath_sq'] = final_test['TotalBath_sq'].fillna(train_x['TotalBath_sq'].mean())
final_test['TotalBath_sq'] = final_test['TotalBath_sq'].fillna(train_x['TotalBath_sq'].mean())
final_test['KitchenQual_2'] = final_test['KitchenQual_2'].fillna(train_x['KitchenQual_2'].mean())
final_test['KitchenQual_3'] = final_test['KitchenQual_3'].fillna(train_x['KitchenQual_3'].mean())
final_test['KitchenQual_sq'] = final_test['KitchenQual_sq'].fillna(train_x['KitchenQual_sq'].mean())
final_test['BsmtFinSF1_log'] = final_test['BsmtFinSF1_log'].fillna(train_x['BsmtFinSF1_log'].mean())
final_test['BsmtFinSF2_log'] = final_test['BsmtFinSF2_log'].fillna(train_x['BsmtFinSF2_log'].mean())
final_test['BsmtUnfSF_log'] = final_test['BsmtUnfSF_log'].fillna(train_x['BsmtUnfSF_log'].mean())
final_test['TotalBsmtSF_log'] = final_test['TotalBsmtSF_log'].fillna(train_x['TotalBsmtSF_log'].mean())
final_test['BsmtFullBath_log'] = final_test['BsmtFullBath_log'].fillna(train_x['BsmtFullBath_log'].mean())
final_test['TotalBsmtSF_log'] = final_test['TotalBsmtSF_log'].fillna(train_x['TotalBsmtSF_log'].mean())
final_test['BsmtHalfBath_log'] = final_test['BsmtHalfBath_log'].fillna(train_x['BsmtHalfBath_log'].mean())
final_test['GarageCars_log'] = final_test['GarageCars_log'].fillna(train_x['GarageCars_log'].mean())
final_test['GarageArea_log'] = final_test['GarageArea_log'].fillna(train_x['GarageArea_log'].mean())
final_test['AllSF_log'] = final_test['AllSF_log'].fillna(train_x['AllSF_log'].mean())
final_test['BsmtHalfBath'] = final_test['BsmtHalfBath'].fillna(train_x['BsmtHalfBath'].mean())

In [7]:
# final_test['MiscFeature']=np.nan
dl = learn.dls.test_dl(final_test)
res= learn.get_preds(dl=dl)

In [39]:
test.loc[6,'MiscFeature']

'Shed'

In [47]:
df['MiscFeature'].value_counts(dropna=False)

NaN     1373
Shed      40
Othr       1
Name: MiscFeature, dtype: int64

In [49]:
test['MiscFeature']=np.nan
dl = learn.dls.test_dl(test)
res= learn.get_preds(dl=dl)

In [44]:
res

(tensor([[0.9217]]), None)

In [4]:
cat_x

['MSZoning',
 'LandContour',
 'LotConfig',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'Foundation',
 'Heating',
 'CentralAir',
 'Electrical',
 'GarageType',
 'GarageFinish',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [9]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
data = pd.DataFrame(
    {
        'important_feature_poisson': np.random.poisson(3, 1000),
        'important_feature_dummy': np.random.binomial(1,0.5,1000),
        'random_feature_normal': np.random.normal(0,100,1000),
        'random_feature_dummy': np.random.binomial(1,0.5,1000)
    }
)

data['Y'] = np.random.normal(10,3,1000) * data['important_feature_poisson'] + np.random.normal(10,3,1000) * data['important_feature_dummy']

In [10]:
X = data.drop(['Y'], axis=1)
Y = data['Y']
reg = RandomForestRegressor(random_state=1,oob_score=True)
reg.fit(X, Y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=True,
                      random_state=1, verbose=0, warm_start=False)

In [11]:
features = X.columns.values
importances = reg.feature_importances_
indices = np.argsort(importances)[::-1]



In [12]:
features[indices]

array(['important_feature_poisson', 'random_feature_normal',
       'important_feature_dummy', 'random_feature_dummy'], dtype=object)

In [13]:
features,importances

(array(['important_feature_poisson', 'important_feature_dummy',
        'random_feature_normal', 'random_feature_dummy'], dtype=object),
 array([0.69297502, 0.05833626, 0.2287804 , 0.01990832]))

In [14]:
importances

array([0.69297502, 0.05833626, 0.2287804 , 0.01990832])

In [15]:
X['important_feature_poisson'].unique()

array([ 5,  3,  1,  6,  0,  4,  2,  8,  7,  9, 10, 11])

In [ ]:
https://medium.com/turo-engineering/how-not-to-use-random-forest-265a19a68576
https://www.kdnuggets.com/2019/10/feature-selection-beyond-feature-importance.html

In [19]:
# X = X.as_matrix()/
from collections import defaultdict
from sklearn.model_selection import ShuffleSplit
scores = defaultdict(list)
## Pseudo code:
# For 100 random draw of train / test (70%/30%):
    # fit a random forest 
    # compute the accuracy (acc) 
    # For each feature: 
        # randomly permute the observations of the feature
        # compute the accuracy with random permutation (shuff_acc)
        # compute the decrease in accuracy between acc and shuff_acc
        # store this value
# compute the mean decrease accuracy over the 100 draws for each feature
for train_idx, test_idx in ShuffleSplit(len(X), 100, .3):
    X_train, X_test = X[train_idx], X[test_idx]
    Y_train, Y_test = Y[train_idx], Y[test_idx]
    rf = reg.fit(X_train, Y_train)
    acc = r2_score(Y_test, rf.predict(X_test))
    for i in range(X.shape[1]):
        X_t = X_test.copy()
        np.random.shuffle(X_t[:, i])
        shuff_acc = r2_score(Y_test, rf.predict(X_t))
        scores[features[i]].append((acc-shuff_acc)/acc)
mda_features = [f for f in scores.keys()]
mda_importance = [(np.mean(score)) for score in scores.values()]
mda_indices = np.argsort(mda_importance)

ImportError: cannot import name 'ShuffleSplit' from 'sklearn' (C:\ProgramData\Miniconda3\lib\site-packages\sklearn\__init__.py)

In [20]:
import numpy as np
a = np.array([12.02194951, 12.02194951, 12.02194951, 12.02194951,
       12.02194951, 12.02194951])

In [5]:
res = np.array([a,a,a,a])

In [16]:
res* np.array([[1,2,3,4]])

ValueError: operands could not be broadcast together with shapes (4,6) (1,4) 

In [29]:
weights = np.array([0.1,0.2,0.6,0.1])
weighted_preds = preds * weights[:, None]
final_preds = np.sum(weighted_preds,axis=0)
final_preds

array([12.02194951, 12.02194951, 12.02194951, 12.02194951, 12.02194951,
       12.02194951])

In [30]:
np.array([0.1]*7 + [0.3])

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.3])